export const PERMISSIONS = {
    // Role & Permission Management
    ROLE_MANAGE: 'ROLE_MANAGE',
    ROLE_VIEW: 'ROLE_VIEW',

    // User Management
    USER_MANAGE: 'USER_MANAGE',
    USER_VIEW: 'USER_VIEW',
    USER_CREATE: 'USER_CREATE',
    USER_EDIT: 'USER_EDIT',
    USER_DELETE: 'USER_DELETE',

    // Candidate Management
    CANDIDATE_VIEW: 'CANDIDATE_VIEW',
    CANDIDATE_MANAGE: 'CANDIDATE_MANAGE',
    CANDIDATE_APPROVE: 'CANDIDATE_APPROVE',

    // Job Management
    JOB_VIEW: 'JOB_VIEW',
    JOB_MANAGE: 'JOB_MANAGE',
    JOB_PUBLISH: 'JOB_PUBLISH',

    // Interview Management
    INTERVIEW_VIEW: 'INTERVIEW_VIEW',
    INTERVIEW_MANAGE: 'INTERVIEW_MANAGE',
    INTERVIEW_EVALUATE: 'INTERVIEW_EVALUATE',

    // Department Management
    DEPARTMENT_MANAGE: 'DEPARTMENT_MANAGE',

    // Dashboard
    DASHBOARD_VIEW: 'DASHBOARD_VIEW',

    // Notifications
    NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE',

    // System Administration
    SYSTEM_CONFIG_MANAGE: 'SYSTEM_CONFIG_MANAGE',
    AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW'
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
