spring.application.name=ats

server.port=${SERVER_PORT:8386}

# Supabase PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.wltjwmleeihjrslylpup}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:binhminhdz123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=604800000
jwt.secret-key=${JWT_SECRET_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJZGz2hrl8JUAG3UoaU5CflYqnXYyohSR1SMGKvWfDXlim1c7BAAkV9s80ORDaBDtIhPwkjWSJjW0RKbTvOmWhRTrhp6JTr6b5UNQnvZAz8fXzphWR4HBsAszLgMIXpEc5gVx7U8UQZk3ayCxxV2fH7WKE8Md9YOqu+RS+XkIfXRj/aT652J3rj7a6kATiQZWyFQQ8xLry/K1L8kGUdH1l5mITyHFIrTzGmLTO6owDHllHGcyS64BD33KDTOuSwb6PKqzDaoZ/3FkyZy62e5tfi5fepORSFpW4KxsMiMyjhlqarsTyZv+KCPwa0jYFo7rCdF+bermtQLsadnqKJCoQIDAQAB}